main:ConcreteSubjectA.o ConcreteSubjectB.o ConcreteObserverA.o AbstractSubject.o
	g++ Application.cpp -o test.exe ConcreteSubjectA.o ConcreteSubjectB.o ConcreteObserverA.o AbstractSubject.o

ConcreteSubjectA.o:
	g++ -c ConcreteSubjectA.cpp

ConcreteSubjectB.o:
	g++ -c ConcreteSubjectB.cpp

ConcreteObserverA.o:
	g++ -c ConcreteObserverA.cpp

AbstractSubject.o:
	g++ -c AbstractSubject.cpp