main: ConcreteTemplateClass.o TemplateMethodClass.o
	g++  Application.cpp -o test.exe ConcreteTemplateClass.o TemplateMethodClass.o
	
ConcreteTemplateClass.o: 
	g++ -c ConcreteTemplateClass.cpp

TemplateMethodClass.o: 
	g++ -c TemplateMethodClass.cpp